# Generated by Django 4.2 on 2023-10-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_content_author_alter_content_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(upload_to='media/content'),
        ),
    ]
